events {
    worker_connections 1024;
}

http {
    # Buffers and sizes
    client_max_body_size 3G;
    client_body_buffer_size 1M;
    client_header_buffer_size 16k;
    large_client_header_buffers 4 16k;

    # Timeouts
    client_body_timeout 3600s;
    client_header_timeout 3600s;
    keepalive_timeout 3600s;
    send_timeout 3600s;

    # Otimizações de I/O
    client_body_temp_path /var/lib/nginx/tmp/client_body;
    client_body_in_file_only clean;
    aio threads;
    directio 1M;
    output_buffers 2 1M;

    include /etc/nginx/conf.d/app.conf;
}
