north_mg_cities = {
    "1": "Águas Vermelhas",
    "2": "Berizal",
    "3": "Bocaiuva",
    "4": "Bonito de Minas",
    "5": "Botumirim",
    "6": "Brasília de Minas",
    "7": "Buritizeiro",
    "8": "Campo Azul",
    "9": "Capitão Eneas",
    "10": "Catuti",
    "11": "Chapada Gaucha",
    "12": "Claro dos Poções",
    "13": "Cônego Marinho",
    "14": "Coração de Jesus",
    "15": "Cristália",
    "16": "Curral de Dentro",
    "17": "Divisa Alegre",
    "18": "Engenheiro Navarro",
    "19": "Espinosa",
    "20": "Francisco Dumont",
    "21": "Francisco Sá",
    "22": "Fruta de Leite",
    "23": "Gameleiras",
    "24": "Glaucilândia",
    "25": "Grão Mogol",
    "26": "Guaraciama",
    "27": "Ibiai",
    "28": "Ibiracatu",
    "29": "Icaraí de Minas",
    "30": "Indaiabira",
    "31": "Itacambira",
    "32": "Itacarambi",
    "33": "Jaiba",
    "34": "Janaúba",
    "35": "Januária",
    "36": "Japonvar",
    "37": "Jequitaí",
    "38": "Josenópolis",
    "39": "Juramento",
    "40": "Juvenília",
    "41": "Lagoa dos Patos",
    "42": "Lassance",
    "43": "Lontra",
    "44": "Luislandia",
    "45": "Mamonas",
    "46": "Manga",
    "47": "Matias Cardoso",
    "48": "Mato Verde",
    "49": "Mirabela",
    "50": "Miravania",
    "51": "Montalvânia",
    "52": "Monte Azul",
    "53": "Montes Claros",
    "54": "Montezuma",
    "55": "Ninheira",
    "56": "Nova Porteirinha",
    "57": "Novorizonte",
    "58": "Olhos-d’Água",
    "59": "Padre Carvalho",
    "60": "Pai Pedro",
    "61": "Patis",
    "62": "Pedras de Maria da Cruz",
    "63": "Pintopolis",
    "64": "Pirapora",
    "65": "Ponto Chique",
    "66": "Porteirinha",
    "67": "Riachinho",
    "68": "Riacho dos Machados",
    "69": "Rio Pardo de Minas",
    "70": "Rubelita",
    "71": "Salinas",
    "72": "Santa Cruz de Salinas",
    "73": "Santa Fé de Minas",
    "74": "Santo Antonio do Retiro",
    "75": "São Francisco",
    "76": "São João da Lagoa",
    "77": "São João da Ponte",
    "78": "São João das Missões",
    "79": "São João do Pacuí",
    "80": "São João do Paraiso",
    "81": "São Romão",
    "82": "Serranópolis de Minas",
    "83": "Taiobeiras",
    "84": "Ubai",
    "85": "Urucuia",
    "86": "Vargem Grande do Rio Pardo",
    "87": "Várzea da Palma",
    "88": "Varzelandia",
    "89": "Verdelandia",
}
