services:
  app:
    container_name: fire-control-api-dev-api
    extends:
      file: base.yml
      service: app
    env_file:
      - ../variables/dev
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 5000
      --reload
      --reload-dir /api

  postgres:
    container_name: fire-control-api-dev-postgres
    extends:
      file: base.yml
      service: postgres
    volumes:
      - ../containers/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql
    env_file:
      - ../variables/dev

  redis:
    container_name: fire-control-api-dev-redis
    extends:
      file: base.yml
      service: redis

  minio:
    container_name: fire-control-api-dev-minio
    extends:
      file: base.yml
      service: minio
    env_file:
      - ../variables/dev

  nginx:
    container_name: fire-control-api-dev-nginx
    extends:
      file: base.yml
      service: nginx

  seeder:
    container_name: fire-control-api-dev-seeder
    extends:
      file: base.yml
      service: seeder
    env_file:
      - ../variables/dev

volumes:
  postgres:
    name: fire-control-api-dev-postgres
  redis:
    name: fire-control-api-dev-redis
  minio:
    name: fire-control-api-dev-minio

networks:
  fire-control-api:
    name: fire-control-api-dev-network
    driver: bridge
