services:
  api:
    extends:
      file: base.yml
      service: app
    container_name: fire-control-api-test-api
    build:
      context: ../../
      dockerfile: deploy/containers/fastapi/Dockerfile
      args:
        - TEST=true
    volumes:
      - ../../source/api:/api
      - ../../source/tests:/tests
    env_file:
      - ../variables/test
    command: >
      pytest
      --cov=/api
      --cov-report=term-missing
      --cov-report=markdown:/tests/coverage.md
      /tests

  postgres:
    container_name: fire-control-api-test-postgres
    extends:
      file: base.yml
      service: postgres
    volumes:
      - ../containers/postgres/init-test.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql
    env_file:
      - ../variables/test

  redis:
    container_name: fire-control-api-test-redis
    extends:
      file: base.yml
      service: redis

  minio:
    container_name: fire-control-api-test-minio
    extends:
      file: base.yml
      service: minio
    env_file:
      - ../variables/test

  seeder:
    container_name: fire-control-api-test-seeder
    extends:
      file: base.yml
      service: seeder
    env_file:
      - ../variables/test

volumes:
  postgres:
    name: fire-control-api-test-postgres
  redis:
    name: fire-control-api-test-redis
  minio:
    name: fire-control-api-test-minio

networks:
  fire-control-api:
    name: fire-control-api-test-network
    driver: bridge
